//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendar.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calendar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AutoStart on login.
        /// </summary>
        public static string CheckBoxAutoStart {
            get {
                return ResourceManager.GetString("CheckBoxAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sync with Google Calendar.
        /// </summary>
        public static string CheckBoxGoogleSync {
            get {
                return ResourceManager.GetString("CheckBoxGoogleSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Always on background.
        /// </summary>
        public static string CheckBoxToBackground {
            get {
                return ResourceManager.GetString("CheckBoxToBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string ContextMenuClose {
            get {
                return ResourceManager.GetString("ContextMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete event.
        /// </summary>
        public static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Event.
        /// </summary>
        public static string ContextMenuEditEvet {
            get {
                return ResourceManager.GetString("ContextMenuEditEvet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feedback.
        /// </summary>
        public static string ContextMenuFeedback {
            get {
                return ResourceManager.GetString("ContextMenuFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New event.
        /// </summary>
        public static string ContextMenuNewEvent {
            get {
                return ResourceManager.GetString("ContextMenuNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pin/Unpin.
        /// </summary>
        public static string ContextMenuPinUnpin {
            get {
                return ResourceManager.GetString("ContextMenuPinUnpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string ContextMenuSettings {
            get {
                return ResourceManager.GetString("ContextMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sync with Google Calendar.
        /// </summary>
        public static string ContextMenuSync {
            get {
                return ResourceManager.GetString("ContextMenuSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme.
        /// </summary>
        public static string ContextMenuThemes {
            get {
                return ResourceManager.GetString("ContextMenuThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No description.
        /// </summary>
        public static string ConverterNoDescription {
            get {
                return ResourceManager.GetString("ConverterNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No title.
        /// </summary>
        public static string ConverterNoTitle {
            get {
                return ResourceManager.GetString("ConverterNoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete Note.
        /// </summary>
        public static string DeleteNote {
            get {
                return ResourceManager.GetString("DeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Event.
        /// </summary>
        public static string EditEventWindowTitle {
            get {
                return ResourceManager.GetString("EditEventWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Note.
        /// </summary>
        public static string EditNote {
            get {
                return ResourceManager.GetString("EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string EventAdd {
            get {
                return ResourceManager.GetString("EventAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string EventCancel {
            get {
                return ResourceManager.GetString("EventCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event title field is required.
        /// </summary>
        public static string EventEditNotificationMassage {
            get {
                return ResourceManager.GetString("EventEditNotificationMassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        public static string EventLableData {
            get {
                return ResourceManager.GetString("EventLableData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event Description.
        /// </summary>
        public static string EventLableDescription {
            get {
                return ResourceManager.GetString("EventLableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time.
        /// </summary>
        public static string EventLableTime {
            get {
                return ResourceManager.GetString("EventLableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event Title.
        /// </summary>
        public static string EventLableTitle {
            get {
                return ResourceManager.GetString("EventLableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event is not selected.
        /// </summary>
        public static string EventNotSelectedMassage {
            get {
                return ResourceManager.GetString("EventNotSelectedMassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string EventSave {
            get {
                return ResourceManager.GetString("EventSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Event.
        /// </summary>
        public static string EventWindowTitle {
            get {
                return ResourceManager.GetString("EventWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feedback.
        /// </summary>
        public static string FeedbackWindowTitle {
            get {
                return ResourceManager.GetString("FeedbackWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Google sign-in timed out.
        /// </summary>
        public static string GoogleTimedOutMassage {
            get {
                return ResourceManager.GetString("GoogleTimedOutMassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End Date.
        /// </summary>
        public static string LableEndDate {
            get {
                return ResourceManager.GetString("LableEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End Time.
        /// </summary>
        public static string LableEndTime {
            get {
                return ResourceManager.GetString("LableEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notes.
        /// </summary>
        public static string LableNotes {
            get {
                return ResourceManager.GetString("LableNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string LableSettigs {
            get {
                return ResourceManager.GetString("LableSettigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No Events.
        /// </summary>
        public static string ListboxNoEvents {
            get {
                return ResourceManager.GetString("ListboxNoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event title field is required.
        /// </summary>
        public static string NewEventNotificationMassage {
            get {
                return ResourceManager.GetString("NewEventNotificationMassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Note.
        /// </summary>
        public static string NewNote {
            get {
                return ResourceManager.GetString("NewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note title field is required.
        /// </summary>
        public static string NoteFileMassage {
            get {
                return ResourceManager.GetString("NoteFileMassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note Text.
        /// </summary>
        public static string NoteText {
            get {
                return ResourceManager.GetString("NoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note Title.
        /// </summary>
        public static string NoteTitle {
            get {
                return ResourceManager.GetString("NoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No Notes.
        /// </summary>
        public static string NotsNoNots {
            get {
                return ResourceManager.GetString("NotsNoNots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Black.
        /// </summary>
        public static string ThemeBlack {
            get {
                return ResourceManager.GetString("ThemeBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blue Water.
        /// </summary>
        public static string ThemeBlueWater {
            get {
                return ResourceManager.GetString("ThemeBlueWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hot Pink.
        /// </summary>
        public static string ThemeHotPink {
            get {
                return ResourceManager.GetString("ThemeHotPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MLB.
        /// </summary>
        public static string ThemeMLB {
            get {
                return ResourceManager.GetString("ThemeMLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NBA.
        /// </summary>
        public static string ThemeNBA {
            get {
                return ResourceManager.GetString("ThemeNBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NFL.
        /// </summary>
        public static string ThemeNFL {
            get {
                return ResourceManager.GetString("ThemeNFL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NHL.
        /// </summary>
        public static string ThemeNHL {
            get {
                return ResourceManager.GetString("ThemeNHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USA.
        /// </summary>
        public static string ThemeUSA {
            get {
                return ResourceManager.GetString("ThemeUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на White.
        /// </summary>
        public static string ThemeWhite {
            get {
                return ResourceManager.GetString("ThemeWhite", resourceCulture);
            }
        }
    }
}
